baseURL = "https://springboot.kr/"
title = "SPRINGBOOT.KR"
theme = "github-style"

[params]
  author = "JINWOO"
  description = ""
  github = "nice7677"
  email = "nice7677@naver.com"
  utterances = "nice7677/nice7677.github.io"
  location = "Seoul"